stages:
  - build
  - test
  - deploy

build-stage:
  image: docker:stable
  stage: build
  variable:
    CONTAINER_BUILD_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  # tags:
  #   - byod
  before_script:
    # - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - echo "Login to Gitlab Registry"
  script:
    - echo "Build and push image to registry"
    # - docker build -t $CONTAINER_BUILD_IMAGE .
    # - docker push $CONTAINER_BUILD_IMAGE

test-stage:
  stage: test
  script:
    - echo "Run unit test"

deploy-stage:
  stage: deploy
  before_script:
    - echo "Push to ECR"
  script:
    - echo "Update ECS Service"