include:
  - project: "gds-engineering-bootcamp/templates"
    ref: "main"
    file:
      - .gitlab-aws-cli.yml

stages:
  - build
  - test
  - publish
  - deploy

build-stage:
  image: docker:stable
  stage: build
  variables:
    CONTAINER_BUILD_IMAGE: $CI_REGISTRY_IMAGE:latest
  tags:
    - local
  before_script:
    - echo "Login to Gitlab Registry"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $CONTAINER_BUILD_IMAGE .
    - docker push $CONTAINER_BUILD_IMAGE

test-stage:
  stage: test
  script:
    - echo "Run unit test"

publish-stage:
  extends: .invoke-awscli-commands-with-assumerole
  image:
    name: $CI_REGISTRY/gds-engineering-bootcamp/templates
    entrypoint:
      - '/usr/bin/env'
  tags:
    - local
  variables:
    ROLE_ARN: arn:aws:iam::477843748912:role/gitlab-bootcamp-oidc-role
  stage: publish
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest
    - docker tag $CI_REGISTRY_IMAGE:latest 477843748912.dkr.ecr.ap-southeast-1.amazonaws.com/backend_bootcamp:latest
    - aws ecr get-login-password --region ap-southeast-1 | docker login --username AWS --password-stdin 477843748912.dkr.ecr.ap-southeast-1.amazonaws.com
    - docker push 477843748912.dkr.ecr.ap-southeast-1.amazonaws.com/backend_bootcamp:latest

deploy-stage:
  extends: .invoke-awscli-commands-with-assumerole
  stage: deploy
  tags:
    - local
  variables:
    ROLE_ARN: arn:aws:iam::477843748912:role/gitlab-bootcamp-oidc-role
  script:
    - echo "Update ECS cluster"
    - aws ecs update-service --cluster bootcamp-demo-application --service backend-app --force-new-deployment --region ap-southeast-1